//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlsBook2Lib.CH12.LiveSearchControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlsBook2Lib.CH12.LiveSearchControls.LocalStrings", typeof(LocalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Pager_nextButton_Text {
            get {
                return ResourceManager.GetString("Pager.nextButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Pager_prevButton_Text {
            get {
                return ResourceManager.GetString("Pager.prevButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Page:&amp;nbsp;.
        /// </summary>
        internal static string Pager_resultsPageCell_Text {
            get {
                return ResourceManager.GetString("Pager.resultsPageCell.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query took about {0} seconds..
        /// </summary>
        internal static string ResultStatusTemplate_QueryTook {
            get {
                return ResourceManager.GetString("ResultStatusTemplate.QueryTook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result {0} - {1} of about {2}..
        /// </summary>
        internal static string ResultStatusTemplate_ResultAbout {
            get {
                return ResourceManager.GetString("ResultStatusTemplate.ResultAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched for: {0}.
        /// </summary>
        internal static string ResultStatusTemplate_SearchFor {
            get {
                return ResourceManager.GetString("ResultStatusTemplate.SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Live Search.
        /// </summary>
        internal static string Search_searchButton_Text {
            get {
                return ResourceManager.GetString("Search.searchButton.Text", resourceCulture);
            }
        }
    }
}
